# ASSOCIATION RULES

In [3]:
data=pd.read_excel("C:\\Users\\Admin\\AppData\\Local\\Temp\\Rar$DIa0.393\\Online retail.xlsx")

In [26]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

transactions = data['shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'].apply(lambda x: x.split(','))

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)
df.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [27]:
df.isnull().sum()

 asparagus           0
almonds              0
antioxydant juice    0
asparagus            0
avocado              0
                    ..
whole wheat pasta    0
whole wheat rice     0
yams                 0
yogurt cake          0
zucchini             0
Length: 120, dtype: int64

In [29]:
df.drop_duplicates()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7492,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7493,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
7495,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [33]:
# Apply Apriori
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
frequent_itemsets

      support                               itemsets
0    0.029303                              (almonds)
1    0.011062                    (antioxydant juice)
2    0.045993                              (avocado)
3    0.012614                                (bacon)
4    0.015525                       (barbecue sauce)
..        ...                                    ...
431  0.014749  (mineral water, olive oil, spaghetti)
432  0.016689   (mineral water, pancakes, spaghetti)
433  0.012420     (mineral water, shrimp, spaghetti)
434  0.010867       (mineral water, spaghetti, soup)
435  0.013584   (mineral water, tomatoes, spaghetti)

[436 rows x 2 columns]

In [32]:
# Generate the association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(mineral water),(almonds),0.299825,0.029303,0.010867,0.036246,1.236923,0.002082,1.007204,0.273564
1,(almonds),(mineral water),0.029303,0.299825,0.010867,0.370861,1.236923,0.002082,1.112909,0.197325
2,(avocado),(chocolate),0.045993,0.203765,0.010285,0.223629,1.097484,0.000914,1.025586,0.093108
3,(chocolate),(avocado),0.203765,0.045993,0.010285,0.050476,1.097484,0.000914,1.004722,0.111557
4,(avocado),(french fries),0.045993,0.192897,0.011644,0.253165,1.312432,0.002772,1.080697,0.249532
...,...,...,...,...,...,...,...,...,...,...
953,"(mineral water, spaghetti)",(tomatoes),0.085193,0.092373,0.013584,0.159453,1.726183,0.005715,1.079805,0.459864
954,"(tomatoes, spaghetti)",(mineral water),0.030080,0.299825,0.013584,0.451613,1.506253,0.004566,1.276789,0.346524
955,(mineral water),"(tomatoes, spaghetti)",0.299825,0.030080,0.013584,0.045307,1.506253,0.004566,1.015951,0.480025
956,(tomatoes),"(mineral water, spaghetti)",0.092373,0.085193,0.013584,0.147059,1.726183,0.005715,1.072532,0.463502
957,(spaghetti),"(mineral water, tomatoes)",0.230157,0.034737,0.013584,0.059022,1.699106,0.005589,1.025808,0.534466

In [34]:
rules_sorted=rules.sort_values(by='lift',ascending=False)
rules_sorted

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
524,(olive oil),(whole wheat pasta),0.087910,0.040753,0.011062,0.125828,3.087575,0.007479,1.097320,0.741288
525,(whole wheat pasta),(olive oil),0.040753,0.087910,0.011062,0.271429,3.087575,0.007479,1.251888,0.704846
910,"(mineral water, milk)",(soup),0.067922,0.071221,0.012420,0.182857,2.567474,0.007583,1.136618,0.655001
915,(soup),"(mineral water, milk)",0.071221,0.067922,0.012420,0.174387,2.567474,0.007583,1.128953,0.657327
396,(herb & pepper),(ground beef),0.066757,0.136425,0.022899,0.343023,2.514365,0.013792,1.314468,0.645368
...,...,...,...,...,...,...,...,...,...,...
374,(green tea),(low fat yogurt),0.168834,0.095284,0.010867,0.064368,0.675534,-0.005220,0.966957,-0.366236
95,(champagne),(mineral water),0.054725,0.299825,0.010867,0.198582,0.662324,-0.005541,0.873669,-0.350376
94,(mineral water),(champagne),0.299825,0.054725,0.010867,0.036246,0.662324,-0.005541,0.980826,-0.421348
174,(mineral water),(cookies),0.299825,0.060353,0.010479,0.034951,0.579115,-0.007616,0.973678,-0.509320
175,(cookies),(mineral water),0.060353,0.299825,0.010479,0.173633,0.579115,-0.007616,0.847293,-0.436128

# INTERVIEW QUESTIONS:

# 1.	What is lift and why is it important in Association rules?

In [ ]:
Lift is a measure used in association rule mining to evaluate the strength of an association between two items or itemsets. In simple terms, it helps to identify how much more likely it is for two items to be found together than would be expected by chance.

IMPORTANCE:
   Lift is important in association rules because it shows how much more likely two items are to occur together than by random
chance. A higher lift value indicates a stronger and more significant association between the items, helping to identify
meaningful patternsÂ inÂ theÂ data.

# 2.	What is support and Confidence. How do you calculate them?

In [ ]:
SUPPORT:
    Support is a number of transactions in which antecedent and consequent appear in the data
CALCULATION:
    Transaction with antecedent and consequent / Total Transactions
CONFIDENCE:
    Confidence is a number of antecedent transactions that also have the consequent item set
CALCULATION:
    Transactions with antecedent and consequent /Transaction with antecedent

# 3.	What are some limitations or challenges of Association rules mining?

In [ ]:
1.Too Many Rules: You might get lots of rules, many of which could be trivial or redundant.

2.Interpreting Rules: It can be hard to understand which rules are useful or meaningful.

3.Binary Data: The technique usually doesnâ€™t consider how much or how often items are bought.

5.Data Quality: Poor data quality can lead to misleadingÂ results.